#!/bin/bash
fallocate -l 4GB /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile none swap defaults 0 0" >> /etc/fstab
ln -sf /usr/share/zoneinfo/America/Mexico_City /etc/localtime
hwclock --systohc
sed -i '/en_US.UTF-8*/s/^#//g' /etc/locale.gen
sed -i '/es_MX.UTF-8*/s/^#//g' /etc/locale.gen
locale-gen
echo LANG=es_MX.UTF-8 >> /etc/locale.conf
echo KEYMAP=la-latin1 >> /etc/vconsole.conf
echo $1 >> /etc/hostname
echo -e '127.0.0.1\tlocalhost' >> /etc/hosts
echo -e '::1\t\tlocalhost' >> /etc/hosts
echo -e '127.0.1.1\t'$1'.localdomain\t'$1'' >> /etc/hosts
echo "Cambiar contraseña root y verificarla"
passwd
pacman -Sy grub efibootmgr networkmanager dhcpcd base-devel linux-zen-headers git xdg-utils xdg-user-dirs p7zip unzip zip
sed -i '55s/base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck/base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems fsck/g' /etc/mkinitcpio.conf
mkinitcpio -p linux-zen
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
if [[ "$2" =~  (sd[a-zA-Z]) ]]; then
    a=$(blkid /dev/$22)
else
    a=$(blkid /dev/$2p2)
fi
a1=${a[@]:17:36}
sed -i '7s/""/"cryptdevice=UUID='$a1':'$3' root=\/dev\/mapper\/'$3'"/g' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager
useradd -mG wheel $4
echo "colocar contraseña para $4"
passwd $4
sed -i '125s/# //g' /etc/sudoers
mv rec.zip /home/$4
mv nemo /home/$4
mv rootinstaller /root
mv after /home/$4/
unzip Zipher.zip
mv Zipher /boot/grub/themes/
echo "GRUB_THEME=/boot/grub/themes/Zipher/theme.txt" >> /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
exit
