#!/bin/bash

# Desinstalar interfaz gráfica actual (ajustar según corresponda)
if pacman -Qs xfce4 &> /dev/null; then
  sudo pacman -Rcns --noconfirm xfce4 xfce4-goodies
elif pacman -Qs gnome &> /dev/null; then
  sudo pacman -Rcns --noconfirm gnome gnome-extra
elif pacman -Qs kde &> /dev/null; then
  sudo pacman -Rcns --noconfirm plasma-meta kde-applications
else
  echo "No se encontró una interfaz gráfica instalada."
fi

# Desinstalar paquetes relacionados con Xorg
paquetes_xorg=$(sudo pacman -Q | grep xorg)
while IFS= read -r paquete; do
    sudo pacman -R --noconfirm "$paquete"
done <<< "$paquetes_xorg"

sudo pacman -S --noconfirm xorg plasma sddm sddm-kcm latte-dock

chmod +x installrootcfg
mv icomoon.zip /home/$1
mv iosevka.zip /home/$1
mv kitty.conf /home/$1
mv installrootcfg /home/$1
mv Hack.zip /home/$1
mv .zshrc /home/$1
mv color.ini /home/$1
mv .p10k.zsh /home/$1
cd ~
sudo pacman -S --noconfirm firewalld gparted htop clamav gimp openssh wget neovim

# Instalaciones personalizadas
mkdir -p ~/Desktop/$1/repos
cd ~/Desktop/$1/repos
git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si
sudo pacman -Sy --needed --noconfirm linux-firmware-qlogic alsa-firmware broadcom-wl-dkms libffado libmtp android-udev libraw1394
paru -S --needed wd719x-firmware upd72020x-fw aic94xx-firmware b43-firmware bluez-firmware
sudo pacman -S --needed --noconfirm alsa-utils alsa-tools pulseaudio acpi acpid jq inotify-tools xclip flameshot brightnessctl nemo kitty
paru -S --needed todo-bin
sudo pacman -S --noconfirm gstreamer gst-plugins-bad gst-plugins-base gst-plugins-base-libs gst-plugins-good gst-plugins-ugly xine-lib libdvdcss libdvdread dvd+rw-tools vlc lame
cd ..
mkdir blackarch
cd blackarch
curl -O https://blackarch.org/strap.sh
chmod +x strap.sh
sudo ./strap.sh
sudo pacman -Sy --noconfirm dnsmasq networkmanager-openconnect networkmanager-openvpn networkmanager-pptp networkmanager-vpnc
paru -S kvantum pamac-aur
sudo systemctl enable NetworkManager.service

# Instalaciones personalizadas de fuentes y paquetes
cd /usr/share/fonts
sudo pacman -S --noconfirm p7zip unzip zip
sudo mv /home/$1/iosevka.zip .
sudo unzip iosevka.zip
sudo rm iosevka.zip

sudo mv /home/$1/icomoon.zip .
sudo unzip icomoon.zip
sudo mv icomoon/*.ttf .
sudo rm -rf icomoon

paru -S --needed nerd-fonts-jetbrains-mono ttf-font-awesome ttf-font-awesome-4 ttf-material-design-icons

# Configuraciones adicionales
cd
sudo sed -i '93s/^#//g' /etc/pacman.conf
sudo sed -i '94s/^#//g' /etc/pacman.conf

sudo pacman -Sy
sudo pacman -Sl multilib

paru -S --needed spotify microsoft-edge-stable-bin

sudo pacman -S --noconfirm zsh
sudo usermod --shell /usr/bin/zsh $1

paru -S --needed zsh-syntax-highlighting zsh-autosuggestions
sudo pacman -S --noconfirm locate
sudo updatedb

cd /usr/share
sudo mkdir zsh-sudo
sudo chown $1:$1 zsh-sudo/
cd zsh-sudo
sudo wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh
cd

sudo pacman -S --noconfirm lsd bat

paru -S --needed scrub

cd /usr/share/fonts
sudo mv /home/$1/Hack.zip .
sudo unzip Hack.zip
sudo rm Hack.zip
cd

mv /home/$1/kitty.conf ~/.config/kitty/
mv /home/$1/color.ini ~/.config/kitty/

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

git clone https://github.com/NvChad/Nvchad ~/.config/nvim --depth 1 && nvim

sudo pacman -S --noconfirm mdcat

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k

sudo cp ~/.zshrc /root/
sudo ln -s -f /home/$1/.zshrc /root/.zshrc
sudo usermod --shell /usr/bin/zsh root

sudo cp ~/.p10k.zsh /root/

exit
