#!/bin/bash
pacman -Sy
parted /dev/$1 mklabel bsd
dd bs=1k count=1 if=/dev/zero of=/dev/$1
partprobe
sgdisk /dev/$1 -g
a=$(sgdisk /dev/$1 -F)
sgdisk /dev/$1 -n 1:$a:200M
sgdisk /dev/$1 -t 1:ef00
b=$(sgdisk /dev/$1 -F)
c=$(sgdisk /dev/$1 -E)
sgdisk /dev/$1 -n 2:$b:$c
echo "Configuración de cifrado con luks"
if [[ "$1" =~  (sd[a-zA-Z]) ]]; then
    cryptsetup -y -v luksFormat /dev/$12
    echo "cifrado finalizado"
    cryptsetup open /dev/$12 $2
    mkfs.ext4 /dev/mapper/$2
    mkfs.fat -F32 /dev/$11
    mount /dev/mapper/$2 /mnt
    mkdir /mnt/boot
    mount /dev/$11 /mnt/boot
else
    cryptsetup -y -v luksFormat /dev/$1p2
    echo "cifrado finalizado"
    cryptsetup open /dev/$1p2 $2
    mkfs.ext4 /dev/mapper/$2
    mkfs.fat -F32 /dev/$1p1
    mount /dev/mapper/$2 /mnt
    mkdir /mnt/boot
    mount /dev/$1p1 /mnt/boot
fi
pacstrap /mnt base linux-zen linux-firmware vim $3
genfstab -U /mnt >> /mnt/etc/fstab
chmod +x finish after rootinstaller
mv finish /mnt
mv after /mnt
mv rec.zip /mnt
mv neo /mnt
mv rootinstaller /mnt
mv Zipher.zip /mnt
arch-chroot /mnt ./finish $4 $1 $2 $5
umount -a
reboot
