#!/bin/bash
mkdir -p ~/Desktop/$1/repos
cd ~/Desktop/$1/repos
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
sudo pacman -S --needed --noconfirm alsa-utils alsa-tools pulseaudio acpi acpid inotify-tools xclip flameshot nemo kitty vlc lame p7zip unzip zip neovim
cd ..
mkdir blackarch
cd blackarch
curl -O https://blackarch.org/strap.sh
chmod +x strap.sh
sudo ./strap.sh
sudo pacman -Sy --noconfirm xorg plasma plasma-framework5 sddm sddm-kcm firewalld gparted htop clamav gimp openssh wget
paru -S pamac-aur
paru -S kvantum ttf-jetbrains-mono ttf-font-awesome ttf-font-awesome-4 ttf-material-design-icons
paru -S spotify microsoft-edge-stable-bin
cd /usr/share/fonts
sudo mv /home/$1/iosevka.zip .
sudo unzip iosevka.zip
sudo rm iosevka.zip
sudo mv /home/$1/icomoon.zip .
sudo unzip icomoon.zip
sudo mv icomoon/*.ttf .
sudo rm -rf icomoon
cd
sudo sed -i '90s/^#//g' /etc/pacman.conf
sudo sed -i '91s/^#//g' /etc/pacman.conf
sudo pacman -Sy
sudo pacman -Sl multilib
sudo pacman -S zsh
sudo usermod --shell /usr/bin/zsh $1
paru -S zsh-syntax-highlighting zsh-autosuggestions
sudo pacman -S locate
sudo updatedb
cd /usr/share
sudo mkdir zsh-sudo
sudo chown $1:$1 zsh-sudo/
cd zsh-sudo
sudo wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh
cd
sudo pacman -S lsd bat mdcat
cd /usr/share/fonts
sudo mv /home/$1/Hack.zip .
sudo unzip Hack.zip
sudo rm Hack.zip
cd
mkdir ~/.config/kitty
mv kitty.conf ~/.config/kitty/
mv color.ini ~/.config/kitty/
sudo pacman -S cmake extra-cmake-modules kdecoration qt5-declarative qt5-x11extras
git clone --single-branch --depth=1 https://github.com/Luwx/Lightly.git
cd Lightly && mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF ..
make
sudo make install
git clone https://github.com/Luwx/LightlyShaders
cd LightlyShaders; mkdir qt5build; cd qt5build; cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DQT5BUILD=ON && make && sudo make install && (kwin_x11 --replace &)
sudo unzip desk.zip
mv kdeglobals ~/.config
sudo mv conf/color-schemes .local/share/.
sudo mv conf/icons .local/share/.
sudo mv conf/plasma .local/share/.
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
sudo cp ~/.zshrc /root/
sudo ln -s -f /home/$1/.zshrc /root/.zshrc
sudo usermod --shell /usr/bin/zsh root
sudo cp ~/.p10k.zsh /root/
sudo systemctl enable sddm.service
sudo systemctl enable NetworkManager.service
reboot
