#!/bin/bash
git clone https://github.com/NvChad/starter ~/.config/nvim && nvim
if ( -d "powerlevel10k")
then
	rm -r powerlevel10k
fi
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k

exit
