#!/bin/bash
pacman -Sy
parted /dev/sd$1 mklabel bsd
dd bs=1k count=1 if=/dev/zero of=/dev/sd$1
partprobe
sgdisk /dev/sd$1 -g
a=$(sgdisk /dev/sd$1 -F)
sgdisk /dev/sd$1 -n 1:$a:200M
sgdisk /dev/sd$1 -t 1:ef00
b=$(sgdisk /dev/sd$1 -F)
c=$(sgdisk /dev/sd$1 -E)
sgdisk /dev/sd$1 -n 2:$b:$c
echo "Configuración de cifrado con luks"
cryptsetup -y -v luksFormat /dev/sd$12
echo "cifrado finalizado"
cryptsetup open /dev/sd$12 $2
mkfs.ext4 /dev/mapper/$2
mkfs.fat -F32 /dev/sd$11
mount /dev/mapper/$2 /mnt
mkdir /mnt/boot
mount /dev/sd$11 /mnt/boot
pacstrap /mnt base linux-zen linux-firmware vim neovim $3
genfstab -U /mnt >> /mnt/etc/fstab
chmod +x install2 install3 install4 installgpu installrootcfg sharedfuncs
mv install2 /mnt
mv install3 /mnt
mv install4 /mnt
mv installgpu /mnt
mv icomoon.zip /mnt
mv iosevka.zip /mnt
mv kitty.conf /mnt
mv installrootcfg /mnt
mv Hack.zip /mnt
mv .zshrc /mnt
mv color.ini /mnt
mv .p10k.zsh /mnt
mv sharedfuncs /mnt
arch-chroot /mnt
umount -a
