#!/bin/bash
fallocate -l 4GB /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile none swap defaults 0 0" >> /etc/fstab
ln -sf /usr/share/zoneinfo/America/Mexico_City /etc/localtime
hwclock --systohc
sed -i '/en_US.UTF-8*/s/^#//g' /etc/locale.gen
sed -i '/es_MX.UTF-8*/s/^#//g' /etc/locale.gen
locale-gen
echo LANG=es_MX.UTF-8 >> /etc/locale.conf
echo KEYMAP=la-latin1 >> /etc/vconsole.conf
echo $1 >> /etc/hostname
echo -e '127.0.0.1\tlocalhost' >> /etc/hosts
echo -e '::1\t\tlocalhost' >> /etc/hosts
echo -e '127.0.1.1\t'$1'.localdomain\t'$1'' >> /etc/hosts
echo "Cambiar contraseña y verificarla"
passwd
pacman -Sy grub efibootmgr networkmanager dhcpcd base-devel linux-zen-headers git xdg-utils xdg-user-dirs
sed -i '55s/base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck/base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems fsck/g' /etc/mkinitcpio.conf
mkinitcpio -p linux-zen
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
a=$(blkid /dev/sd$22)
a1=${a[@]:17:36}
sed -i '7s/""/"cryptdevice=UUID='$a1':'$3' root=\/dev\/mapper\/'$3'"/g' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager
useradd -mG wheel $4
echo "colocar contraseña para nuevo usuario"
passwd $4
sed -i '108s/# //g' /etc/sudoers
mv rec.zip /home/$4
mv desktopwall.zip /home/$4
mv desk.zip /home/$4
mv installrootcfg /root
mv install3 /home/$4/
exit
